### ISSUE TITLE
Could it used as mdevd replacement?

### ISSUE THREAD

**Issue by pwFoo** [pilebones/go-udev#15]
I use mdevd / mdevd-coldplug for coldplug and hotplug of devices. 

Is it possible with go-udev too?

**Comment by pilebones** [comment]
Hello,

Thanks for your interest, I think it could be possible to replace `mdev` by `go-udev` depending on the complexity of your use case. Otherwise you should probably implement your use case using the API provided by `go-udev`.

`go-udev` allow to:
* Scan existing devices in /sys as mdevd-coldplug but don't tell to the kernel to generate an event, it build a list of devices with metadata objects to manage them.
* Listen to the kernel channel related to udev events and build related objects to manage them.
* Provide an API to implement another complex use cases.

How do you use mdevd ?

**Comment by pwFoo** [comment]
I built a custom initrd based on busybox with a driver detection loop (bash command) and mdevd for device coldplug / hotplug to handle kernel modules at boot and run time to handle hdd, usb sticks, ...

At the moment I play with u-root (go based) and would need a way to load all the needed kernel modules during boot and os run time (usb hotplug events, loading needed kernel modules).

I'm new with golang. So I don't know which solutions available or could fit my needs and found your go-udev as possible way.

**Comment by pilebones** [comment]
Initially, `go-udev` has been developped from scratch to autodetect at runtime a GPS device already pluggued or when hot-plug or then when unplug; for this project still in developpement: https://github.com/pilebones/go-gpsd

I think it is not so different than your use case, you could inspire you by this implementation:
https://github.com/pilebones/go-gpsd/blob/feature/deconnect-device/autodetect.go#L43

It is a little bit treaky if you are new with Go but not impossible :)
I hope it could help you. 

Anyway, feel free to ask another questions, I will do my best to react quickly and effectively.

**Comment by pwFoo** [comment]
Go is really interesting, but maybe an easier task would be better to start with it *g*
I have to take a deeper look how it could be done and what should work for my case.

Thank you very much for answering my questions and helping here!

**Comment by pilebones** [comment]
To start with it "g" ...? Missing ending ?

Indeed, feel free to ask another questions if `go-udev` could answer to your use-case, your are welcome and good luck for your research.

At this time, I close this issue.
